### ISSUE TITLE
kuka - setup

### ISSUE THREAD

**Issue by kallysalt** [RROS-Lab/iiwa_cam#5]
How to setup the network interface on the ROS machine to be in the same subnet?

**Comment by PeijieXu** [comment]
You need to make sure that your computer and the robot are on the same LAN (you can use a network cable to connect your computer to the LAN).

By using the **ifconfig** command, if only the last field of your IP address is different from the IP address of the robot, then it is probably that the ROS machine is already in a subnet with the robot. At this point, you can use the **ping**  command to check if they (the ROS machine and the robot) are connected.
