### ISSUE TITLE
Change control mode using ROS service of the oiginal iiwa_stack

### ISSUE THREAD

**Issue by PeijieXu** [RROS-Lab/iiwa_cam#8]
When we want to change control mode using the ROS service of the original iiwa_stack, it cannot move after we change the mode.

May need to develop our own ROS service for changing modes.

**Comment by omeym** [comment]
Is there any error message that is displayed or the robot just doesn't move?

**Comment by PeijieXu** [comment]
> Is there any error message that is displayed or the robot just doesn't move?
There

**Comment by PeijieXu** [comment]
> Is there any error message that is displayed or the robot just doesn't move?

There is no error message, the robot doesn't move while the impedance control feature remains (you can push the robot). 

We sent several commands trying to move the robot under the impedance control mode, and it didn't move. Sometimes it will execute a sequence of motions that had been lined up after we change the control mode back to position control mode.

**Comment by PeijieXu** [comment]
The issue is addressed by adding a default value to nullspace_stiffness and nullspace_damping
